-- =====================================================================
-- URBAN CART - DATA ANALYST PORTFOLIO PROJECT
-- FINAL PRODUCTION-READY & OPTIMIZED SQL QUERIES (Q1 - Q25)
-- Developed by: Sobuj (Excel, Power BI & SQL Data Analyst)
-- =====================================================================

-- Q1. How many total orders has UrbanCart received so far?
SELECT COUNT(DISTINCT order_id) AS "Total_Orders"
FROM public.FactOrders;


-- Q2. Which cities generate the highest number of orders & revenue?
WITH Order_Revenue AS (
    SELECT 
        o.order_id,
        o.customer_id,
        SUM(oi.quantity * p.unit_price) AS order_total
    FROM public.FactOrders o
    JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY o.order_id, o.customer_id
)
SELECT 
    c.city AS "City",
    COUNT(DISTINCT r.order_id) AS "Total_Orders",
    ROUND(SUM(r.order_total), 2) AS "Total_Revenue"
FROM public.DimCustomers c
JOIN Order_Revenue r ON c.customer_id = r.customer_id
GROUP BY c.city
ORDER BY "Total_Revenue" DESC;


-- Q3. What percent of total customers uses gmail?
WITH Gmail_Count AS (
    SELECT COUNT(*) AS Gmail_Users 
    FROM public.DimCustomers 
    WHERE email LIKE '%@gmail.com'
),
Total_Count AS (
    SELECT COUNT(*) AS Total_Customers 
    FROM public.DimCustomers
)
SELECT 
    g.Gmail_Users AS "Total_Gmail_User",
    t.Total_Customers AS "Total_Customers", 
    ROUND((g.Gmail_Users * 100.0) / t.Total_Customers, 2) AS "Gmail_Percentage(%)"
FROM Gmail_Count g, Total_Count t;


-- Q4. What is the monthly trend of total orders over time?
SELECT 
    DATE_TRUNC('month', order_date) AS "Month", 
    COUNT(DISTINCT order_id) AS "Total_Orders"
FROM public.FactOrders
GROUP BY 1
ORDER BY 1 ASC;


-- Q6. What is the total revenue generated by UrbanCart?
SELECT ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id;


-- Q7. Which product categories contribute the most to total revenue?
SELECT 
    p.category AS "Category_Name", 
    ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC;


-- Q8. Which individual products generate the highest revenue?
SELECT 
    p.product_name AS "Product_Name", 
    ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY "Total_Revenue" DESC
LIMIT 10;


-- Q9. What is the average order value (AOV) and Average Basket Size?
WITH Order_Metrics AS (
    SELECT 
        oi.order_id,
        SUM(oi.quantity) AS total_items,
        SUM(oi.quantity * p.unit_price) AS order_value
    FROM public.FactOrderItems oi
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY oi.order_id
)
SELECT 
    ROUND(AVG(order_value), 2) AS "Average_Order_Value",
    ROUND(AVG(total_items), 2) AS "Average_Basket_Size"
FROM Order_Metrics;


-- Q10. Which products are at risk of stock-out due to high sales volume and low inventory?
SELECT 
    p.product_name AS "Product_Name",
    p.stock AS "Current_Stock",
    SUM(oi.quantity) AS "Sales_Volume"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id
JOIN public.FactOrders o ON oi.order_id = o.order_id
WHERE o.order_date >= DATE '2025-11-01'  -- আপনার ডাটার টাইমলাইন অনুযায়ী ফিক্সড ডেট
GROUP BY p.product_name, p.stock
HAVING p.stock < SUM(oi.quantity)
ORDER BY "Current_Stock" ASC, "Sales_Volume" DESC;


-- Q11. Which customers contribute the highest total revenue?
WITH Customer_Spend AS (
    SELECT 
        o.customer_id,
        SUM(oi.quantity * p.unit_price) AS total_spent
    FROM public.FactOrders o
    JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY o.customer_id
)
SELECT 
    c.customer_id,
    c.full_name,
    ROUND(cs.total_spent, 2) AS "Total_Spent"
FROM Customer_Spend cs
JOIN public.DimCustomers c ON c.customer_id = cs.customer_id
ORDER BY "Total_Spent" DESC
LIMIT 10;


-- Q12. Generate a list of cancellation rate by city; also the cancellation rate for customers.
-- (Part A: By City)
SELECT 
    c.city AS "City",
    COUNT(DISTINCT o.order_id) AS "Total_Orders",
    COUNT(DISTINCT CASE WHEN o.status = 'Cancelled' THEN o.order_id END) AS "Cancelled_Orders",
    ROUND((COUNT(DISTINCT CASE WHEN o.status = 'Cancelled' THEN o.order_id END) * 100.0) / COUNT(DISTINCT o.order_id), 2) AS "Cancellation_Rate(%)"
FROM public.DimCustomers c
JOIN public.FactOrders o ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY "Cancellation_Rate(%)" DESC;

-- (Part B: By Customer)
SELECT 
    c.customer_id,
    c.full_name,
    COUNT(DISTINCT o.order_id) AS "Total_Orders",
    COUNT(DISTINCT CASE WHEN o.status = 'Cancelled' THEN o.order_id END) AS "Cancelled_Orders",
    ROUND((COUNT(DISTINCT CASE WHEN o.status = 'Cancelled' THEN o.order_id END) * 100.0) / NULLIF(COUNT(DISTINCT o.order_id), 0), 2) AS "Cancellation_Rate(%)"
FROM public.DimCustomers c
JOIN public.FactOrders o ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.full_name
ORDER BY "Cancellation_Rate(%)" DESC;


-- Q13. Do male and female customers show different purchasing patterns by category?
SELECT 
    c.gender AS "Gender",
    p.category AS "Category",
    COUNT(DISTINCT o.order_id) AS "Total_Orders",
    SUM(oi.quantity) AS "Total_Quantity_Purchased",
    ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue",
    ROUND(SUM(oi.quantity)::NUMERIC / COUNT(DISTINCT o.order_id), 2) AS "Avg_Basket_Size_Per_Order",
    ROUND(SUM(oi.quantity * p.unit_price)::NUMERIC / COUNT(DISTINCT o.order_id), 2) AS "Avg_Order_Value_AOV"
FROM public.DimCustomers c
JOIN public.FactOrders o ON c.customer_id = o.customer_id
JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
JOIN public.DimProducts p ON oi.product_id = p.product_id
WHERE c.gender IS NOT NULL 
GROUP BY c.gender, p.category
ORDER BY c.gender ASC, "Total_Revenue" DESC;


-- Q14. How does customer purchasing behavior change over time since account creation?
WITH Customer_Monthly_Order AS (
    SELECT 
        o.customer_id,
        o.order_id,
        o.order_date,
        SUM(oi.quantity * p.unit_price) AS order_revenue
    FROM public.FactOrders o
    JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY o.customer_id, o.order_id, o.order_date
)
SELECT
    c.customer_id,
    c.full_name,
    c.created_at AS account_creation_date,
    ((EXTRACT(YEAR FROM m.order_date) - EXTRACT(YEAR FROM c.created_at)) * 12 + 
     (EXTRACT(MONTH FROM m.order_date) - EXTRACT(MONTH FROM c.created_at))) AS month_since_signup,
    COUNT(DISTINCT m.order_id) AS total_orders,
    ROUND(SUM(m.order_revenue), 2) AS total_spent,
    ROUND(AVG(m.order_revenue), 2) AS avg_order_value
FROM public.DimCustomers c
JOIN Customer_Monthly_Order m ON c.customer_id = m.customer_id
GROUP BY
    c.customer_id,
    c.full_name,
    c.created_at,
    ((EXTRACT(YEAR FROM m.order_date) - EXTRACT(YEAR FROM c.created_at)) * 12 + 
     (EXTRACT(MONTH FROM m.order_date) - EXTRACT(MONTH FROM c.created_at)))
ORDER BY c.customer_id, month_since_signup;


-- Q15. Generate a list of customers who ordered in October but didn’t order in December.
SELECT DISTINCT c.customer_id, c.full_name, c.email
FROM public.DimCustomers c
JOIN public.FactOrders o ON c.customer_id = o.customer_id
WHERE DATE_TRUNC('month', o.order_date) = DATE '2025-10-01'
  AND NOT EXISTS (
      SELECT 1 
      FROM public.FactOrders o2 
      WHERE o2.customer_id = c.customer_id 
        AND DATE_TRUNC('month', o2.order_date) = DATE '2025-12-01'
  );


-- Q16. Generate a list of customers who ordered both in October & December.
SELECT DISTINCT c.customer_id, c.full_name, c.email
FROM public.DimCustomers c
JOIN public.FactOrders o ON c.customer_id = o.customer_id
WHERE DATE_TRUNC('month', o.order_date) = DATE '2025-10-01'
INTERSECT
SELECT DISTINCT c.customer_id, c.full_name, c.email
FROM public.DimCustomers c
JOIN public.FactOrders o ON c.customer_id = o.customer_id
WHERE DATE_TRUNC('month', o.order_date) = DATE '2025-12-01';


-- Q17. Which payment methods are used most frequently?
SELECT 
    method AS "Payment_Method",
    COUNT(payment_id) AS "Usage_Count"
FROM public.FactPayment
GROUP BY method
ORDER BY "Usage_Count" DESC;


-- Q18. Is there any relationship between payment method and order status?
WITH Method_Status_Counts AS (
    SELECT 
        fp.method AS "Payment_Method",
        fo.status AS "Order_Status",
        COUNT(DISTINCT fo.order_id) AS "Total_Orders"
    FROM public.FactPayment fp
    JOIN public.FactOrders fo ON fp.order_id = fo.order_id
    GROUP BY fp.method, fo.status
),
Method_Totals AS (
    SELECT 
        "Payment_Method",
        SUM("Total_Orders") AS "Method_Total_Orders"
    FROM Method_Status_Counts
    GROUP BY "Payment_Method"
)
SELECT 
    m."Payment_Method",
    m."Order_Status",
    m."Total_Orders",
    ROUND((m."Total_Orders" * 100.0) / t."Method_Total_Orders", 2) AS "Percentage_Within_Method(%)"
FROM Method_Status_Counts m
JOIN Method_Totals t ON m."Payment_Method" = t."Payment_Method"
ORDER BY m."Payment_Method", m."Total_Orders" DESC;


-- Q19. Do certain cities prefer specific payment methods?
SELECT 
    c.city AS "City",
    fp.method AS "Payment_Method",
    COUNT(fp.payment_id) AS "Usage_Count",
    ROW_NUMBER() OVER (PARTITION BY c.city ORDER BY COUNT(fp.payment_id) DESC) AS "Preference_Rank"
FROM public.DimCustomers c
JOIN public.FactOrders fo ON c.customer_id = fo.customer_id
JOIN public.FactPayment fp ON fo.order_id = fp.order_id
GROUP BY c.city, fp.method
ORDER BY c.city, "Usage_Count" DESC;


-- Q20. Are higher-value orders associated with specific payment methods?
WITH Order_Values AS (
    SELECT 
        fo.order_id,
        SUM(oi.quantity * p.unit_price) AS order_total
    FROM public.FactOrders fo
    JOIN public.FactOrderItems oi ON fo.order_id = oi.order_id
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY fo.order_id
)
SELECT 
    fp.method AS "Payment_Method",
    ROUND(AVG(ov.order_total), 2) AS "Average_Order_Value",
    ROUND(MAX(ov.order_total), 2) AS "Max_Order_Value"
FROM public.FactPayment fp
JOIN Order_Values ov ON fp.order_id = ov.order_id
GROUP BY fp.method
ORDER BY "Average_Order_Value" DESC;


-- Q21. What is the average number of items per order by payment method?
WITH Order_Items AS (
    SELECT 
        order_id,
        SUM(quantity) AS total_items
    FROM public.FactOrderItems
    GROUP BY order_id
)
SELECT 
    fp.method AS "Payment_Method",
    ROUND(AVG(oi.total_items), 2) AS "Average_Items_Per_Order"
FROM public.FactPayment fp
JOIN Order_Items oi ON fp.order_id = oi.order_id
GROUP BY fp.method
ORDER BY "Average_Items_Per_Order" DESC;


-- Q22. Create a list to show the difference between the category average price and product’s price for all the products.
SELECT 
    product_id,
    product_name,
    category,
    unit_price,
    ROUND(AVG(unit_price) OVER(PARTITION BY category), 2) AS "Category_Average_Price",
    ROUND(unit_price - AVG(unit_price) OVER(PARTITION BY category), 2) AS "Price_Difference"
FROM public.DimProducts;


-- Q23. Which product pairs are most frequently purchased together in the same order?
WITH Order_Product_List AS (
    SELECT order_id, product_id 
    FROM public.FactOrderItems
    GROUP BY order_id, product_id
)
SELECT 
    p1.product_name AS "Product_1",
    p2.product_name AS "Product_2",
    COUNT(DISTINCT opl1.order_id) AS "Times_Purchased_Together"
FROM Order_Product_List opl1
JOIN Order_Product_List opl2 ON opl1.order_id = opl2.order_id AND opl1.product_id < opl2.product_id
JOIN public.DimProducts p1 ON opl1.product_id = p1.product_id
JOIN public.DimProducts p2 ON opl2.product_id = p2.product_id
GROUP BY p1.product_name, p2.product_name
ORDER BY "Times_Purchased_Together" DESC
LIMIT 10;


-- Q24. Which product pairs generate the highest total revenue when sold together?
WITH Order_Product_Revenue AS (
    SELECT 
        oi.order_id, 
        oi.product_id,
        SUM(oi.quantity * p.unit_price) AS product_revenue
    FROM public.FactOrderItems oi
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY oi.order_id, oi.product_id
)
SELECT 
    p1.product_name AS "Product_1",
    p2.product_name AS "Product_2",
    COUNT(DISTINCT opr1.order_id) AS "Times_Purchased_Together",
    ROUND(SUM(opr1.product_revenue + opr2.product_revenue), 2) AS "Combined_Revenue"
FROM Order_Product_Revenue opr1
JOIN Order_Product_Revenue opr2 ON opr1.order_id = opr2.order_id AND opr1.product_id < opr2.product_id
JOIN public.DimProducts p1 ON opr1.product_id = p1.product_id
JOIN public.DimProducts p2 ON opr2.product_id = p2.product_id
GROUP BY p1.product_name, p2.product_name
ORDER BY "Combined_Revenue" DESC
LIMIT 10;


-- Q25. Generate a daily report containing the columns Date, Total Orders, Total Items, Completed Orders, Cancelled Orders, Total Revenue 
SELECT
    DATE(o.order_date) AS "Date",
    COUNT(DISTINCT o.order_id) AS "Total_Orders",
    SUM(oi.quantity) AS "Total_Items",
    COUNT(DISTINCT CASE WHEN o.status = 'Delivered' THEN o.order_id END) AS "Completed Orders",
    COUNT(DISTINCT CASE WHEN o.status = 'Cancelled' THEN o.order_id END) AS "Cancelled Orders",
    ROUND(SUM(CASE WHEN o.status = 'Delivered' THEN oi.quantity * p.unit_price ELSE 0 END), 2) AS "Total_Revenue"
FROM public.FactOrders o
JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
JOIN public.DimProducts p ON oi.product_id = p.product_id
GROUP BY DATE(o.order_date)
ORDER BY "Date" DESC;