-- =====================================================================
-- URBAN CART - DATA ANALYST PORTFOLIO PROJECT
-- FINAL PRODUCTION-READY & OPTIMIZED SQL QUERIES (Q1 - Q25)
-- Developed by: Sobuj (Excel, Power BI & SQL Data Analyst)
-- Verified Status Term: 'Completed' | Optimized with: Numeric Group/Order
-- =====================================================================

-- Q1. How many total orders has UrbanCart received so far?
SELECT COUNT(DISTINCT order_id) AS "Total_Orders"
FROM public.FactOrders;


-- Q2. Which cities generate the highest number of orders & revenue?
WITH Order_Revenue AS (
    SELECT 
        o.order_id,
        o.customer_id,
        SUM(oi.quantity * p.unit_price) AS order_total
    FROM public.FactOrders o
    JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY 1, 2
)
SELECT 
    c.city AS "City",
    COUNT(DISTINCT r.order_id) AS "Total_Orders",
    ROUND(SUM(r.order_total), 2) AS "Total_Revenue"
FROM public.DimCustomers c
JOIN Order_Revenue r ON c.customer_id = r.customer_id
GROUP BY 1
ORDER BY 3 DESC;


-- Q3. What percent of total customers uses gmail?
WITH Gmail_Count AS (
    SELECT COUNT(*) AS Gmail_Users 
    FROM public.DimCustomers 
    WHERE email LIKE '%@gmail.com'
),
Total_Count AS (
    SELECT COUNT(*) AS Total_Customers 
    FROM public.DimCustomers
)
SELECT 
    g.Gmail_Users AS "Total_Gmail_User",
    t.Total_Customers AS "Total_Customers", 
    ROUND((g.Gmail_Users * 100.0) / t.Total_Customers, 2) AS "Gmail_Percentage(%)"
FROM Gmail_Count g, Total_Count t;


-- Q4. What is the monthly trend of total orders over time?
SELECT 
    DATE_TRUNC('month', order_date) AS "Month", 
    COUNT(DISTINCT order_id) AS "Total_Orders"
FROM public.FactOrders
GROUP BY 1
ORDER BY 1 ASC;


-- Q6. What is the total revenue generated by UrbanCart?
SELECT ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id;


-- Q7. Which product categories contribute the most to total revenue?
SELECT 
    p.category AS "Category_Name", 
    ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC;


-- Q8. Which individual products generate the highest revenue?
SELECT 
    p.product_name AS "Product_Name", 
    ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;


-- Q9. What is the average order value (AOV) and Average Basket Size?
WITH Order_Metrics AS (
    SELECT 
        oi.order_id,
        SUM(oi.quantity) AS total_items,
        SUM(oi.quantity * p.unit_price) AS order_value
    FROM public.FactOrderItems oi
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY 1
)
SELECT 
    ROUND(AVG(order_value), 2) AS "Average_Order_Value",
    ROUND(AVG(total_items), 2) AS "Average_Basket_Size"
FROM Order_Metrics;


-- Q10. Which products are at risk of stock-out due to high sales volume and low inventory?
SELECT 
    p.product_name AS "Product_Name",
    p.stock AS "Current_Stock",
    SUM(oi.quantity) AS "Sales_Volume"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id
JOIN public.FactOrders o ON oi.order_id = o.order_id
WHERE o.order_date >= DATE '2025-11-01'
GROUP BY 1, 2
HAVING p.stock < SUM(oi.quantity)
ORDER BY 2 ASC, 3 DESC;


-- Q11. Which customers contribute the highest total revenue?
WITH Customer_Spend AS (
    SELECT 
        o.customer_id,
        SUM(oi.quantity * p.unit_price) AS total_spent
    FROM public.FactOrders o
    JOIN public.FactOrderItems oi ON o.order_id = oi.order_id
    JOIN public.DimProducts p ON oi.product_id = p.product_id
    GROUP BY 1
)
SELECT 
    c.customer_id,
    c.full_name,
    ROUND(cs.total_spent, 2) AS "Total_Spent"
FROM Customer_Spend cs
JOIN public.DimCustomers c ON c.customer_id = cs.customer_id
ORDER BY 3 DESC
LIMIT 10;


-- Q12. Generate a list of cancellation rate by city; also the cancellation rate for customers.
-- (Part A: By City)
SELECT 
    c.city AS "City",
    COUNT(DISTINCT o.order_id) AS "Total_Orders",
    COUNT(DISTINCT CASE WHEN LOWER(o.status) = 'cancelled' THEN o.