-- Q6. What is the total revenue generated by UrbanCart?
SELECT ROUND(SUM(oi.quantity * p.unit_price), 2) AS "Total_Revenue"
FROM public.FactOrderItems oi
JOIN public.DimProducts p ON oi.product_id = p.product_id;